name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "*/10 * * * *"
  push:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: andatoshiki/toshiki-productive@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 1a9fe9fe9e668614415b64e3148a4277
          TIMEZONE: Asia/Taipei
